### ISSUE TITLE
How to install it by luarock command?

### ISSUE THREAD

**Issue by zencore-dobetter** [thenumbernine/lua-ext#3]
I tried to install your extension with these command, but failed:
```
luarocks install lua-ext
luarocks install ext-lua
luarocks install ext
luarocks install luaext
luarocks install lua.ext
luarocks install ext.lua
```
The error message is:
```
Error: No results matching query were found for Lua 5.4.
```
so what's your name?
Could you please add Install description block on README.md?

**Comment by thenumbernine** [comment]
I am not posting my projects on the luarocks servers, so you cannot "luarocks install (my project name)".  You have to install the rock from the rockfile that I have provided in my repository.  Like so:
```
git clone https://github.com/thenumbernine/lua-ext
cd lua-ext
luarocks install ext-dev-1.rockspec
``` 
As a general rule, just because a github repository anywhere has a rockspec file does not mean it is posted on the luarocks servers.

**Comment by tobiasBora** [comment]
Since `ext-dev-1.rockspec` does not exist anymore, should one manually create it?

**Comment by thenumbernine** [comment]
I renamed it to `ext.rockspec`

**Comment by tobiasBora** [comment]
I mean, `luarocks install ext.rockspec` fails because it expects a filename with the version. So for now I link `ext-dev-1.rockspec` to `ext.rockspec` but it seems quite dirty. How do you fix this issue on your side?

**Comment by thenumbernine** [comment]
Aha, I didn't realize this about luarocks.  I don't really use luarocks.  I only provide the `.rockspec` files because it is such a popular package management system for Lua.  I will rename them back to the `-dev-1` suffix.

**Comment by tobiasBora** [comment]
Oh I see, thanks. I see you also changed https://github.com/thenumbernine/lua-parser thanks! But I'm curious, how do you develop `lua-parser` without `luarocks`? Because the current file hierarchie does not allow e.g. `require('parser.lua.parser')` that is used everywhere, so without luarocks I need to rename folders etc to recreate the good file structure.

Btw also, any reason you don't publish `ext` and `lua-template`? It would allow to install `lua-parser` in a single step.

**Comment by thenumbernine** [comment]
I describe this in the ["lua-ext" README](https://github.com/thenumbernine/lua-ext).  To get it to run you can do one of the three:
1) Install the `.rockspec`.
2) Move the matching name file (for `lua-ext` it would be `ext.lua`) into the parent directory.
3) Add "?/?.lua" to your `LUA_PATH` environment variable.

I don't like option #2 because it clutters the root directory with filenames that match their respective directories. 

I don't like LuaRocks because its solution is to do the same thing as #1.  I think LuaRocks just puts all installed libraries in the same directory.

This is also why I haven't published my "lua-ext" on LuaRocks, becuase "ext" is such a common name, I'm sure it would cause some kind of naming collisions.  Same with "template", and same with "parser".  I guess there is an art to choosing clever tool/library names, not only to stand out but also to prevent name collisions with everyone else, and I just don't put enough effort into this.

On my own system I added "?/?.lua" to my environment variable.

I first tried giving the `LUA_PATH` a default search file of "?/init.lua" to match the default behavior `LUA_CPATH` search of "?/init.so", but for some reason I preferred naming the library name after the directory name and would just fill my "init.lua"s with one line to require the file named after the folder ....

... after long enough I got rid of the "init.lua"s and just changed the `LUA_PATH` rule from "?/init.lua" to "?/?.lua".

**Comment by tobiasBora** [comment]
Thanks for this.

> Add "?/?.lua" to your LUA_PATH environment variable.

Well, this might not be enough. For instance `parser.lua` requires `parser.lua.parser`, so for this to work I need:
1. to put `PATH_TO_PARENT_FOLDER_OF_CLONE/?.lua` in addition to `?/?.lua` in my path
2. and **rename the folder `lua-parse`** (created when cloning the repository based on github's url) into `parse`.

So for now, with also `lua-ext` installed via luarocks, I need to do:
```
package.path = package.path..';?.lua' .. ';?/?.lua' .. ';/tmp/?.lua' .. ';/home/myname/.luarocks/share/lua/5.3/?.lua'
```
where `/tmp/` is the folder used to clone the repository.

But thanks for this explanation, I thought I was missing some magic trick for this.

> I don't like LuaRocks because its solution is to do the same thing as https://github.com/thenumbernine/lua-ext/issues/1.

What do you mean? LuaRocks seems to create a proper folder hierarchie based on the rules you specified in your `rockspec` file:

```
$ pwd
/home/me/.luarocks/share/lua/5.3
$ tree
.
├── ast.lua
├── ext
│   ├── assert.lua
│   ├── class.lua
│   ├── cmdline.lua
│   ├── coroutine.lua
│   ├── ctypes.lua
│   ├── debug.lua
│   ├── detect_ffi.lua
│   ├── detect_lfs.lua
│   ├── detect_os.lua
│   ├── env.lua
│   ├── fromlua.lua
│   ├── gc.lua
│   ├── gcmem.lua
│   ├── io.lua
│   ├── load.lua
│   ├── math.lua
│   ├── meta.lua
│   ├── number.lua
│   ├── op.lua
│   ├── os.lua
│   ├── path.lua
│   ├── range.lua
│   ├── reload.lua
│   ├── require.lua
│   ├── string.lua
│   ├── table.lua
│   ├── timer.lua
│   ├── tolua.lua
│   └── xpcall.lua
├── ext.lua
├── parser
│   ├── base
│   │   ├── ast.lua
│   │   ├── datareader.lua
│   │   ├── parser.lua
│   │   └── tokenizer.lua
│   ├── grammar
│   │   ├── parser.lua
│   │   └── tokenizer.lua
│   ├── load_xform.lua
│   └── lua
│       ├── ast.lua
│       ├── parser.lua
│       └── tokenizer.lua
├── parser.lua
└── tokenizer.lua
```

**Comment by tobiasBora** [comment]
> This is also why I haven't published my "lua-ext" on LuaRocks, becuase "ext" is such a common name, 

Ahah then you want to be the first publisher if you don't feel like searching for a more unique name ^^

**Comment by thenumbernine** [comment]
Yes LuaRocks functions.  But do you notice how "ast.lua", "ext.lua", "parser.lua", "tokenizer.lua" are all in the root folder?
If two packages decide to have a file of the same name in the root folder, you will have a conflict, potentially overwriting one of them.  I'm sure luarocks will just complain before overwriting one, but either is more severe than my current setup which simply results in a search path choice of precedence.

That's one reason I don't use LuaRocks.  The other is: here's a challenge for you.  Try to setup LuaRocks for multiple versions of Lua at once.  Especially original Lua and LuaJIT.  Last I checked, the most popular choice of action is to simply create two separate copies of LuaRocks with their own separate search paths.  It is a bit of a hassle.

A third reason I don't use it, I think you just taught me today:  LuaRocks has some strict requirements on their rockspec file naming convention, while I don't think any other script environment's package manager has these version-naming requirements.

**Comment by tobiasBora** [comment]
I see, thank you for these details :-)
